### PR TITLE
Fix template oops

### PR DESCRIPTION
**Pull request by webbnh**
## Changes introduced with this PR

Apparently this plugin was created from the Python template.  This PR fixes an omission in the convertion.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by jaredoconnell — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]
So this is just an "example" of *using* the plugin? Huh.

**Comment by webbnh** [comment]
> this is just an "example" of _using_ the plugin?

My understanding (@jaredoconnell or @mfleader, correct me if I'm wrong...) is that there is a ["template repo"](https://github.com/arcalot/arcaflow-plugin-template-python) which gives you everything you need to create a (Python-based) plug-in -- you just clone and rename the repo, fill in the slots, and push it up.  And, there is even a [script which helps you fill in the slots](https://github.com/arcalot/arcaflow-plugin-template-python/blob/main/set-plugin-name.sh).  However, I suspect that this repo was created before the existence of the helper script, and that the "slot" fixed in this PR got missed (and, interestingly, it doesn't seem to actually have an impact...).

**Comment by webbnh** [comment]
_[Working while distracted is a terrible thing...]_

> > this is just an "example" of _using_ the plugin?
> 
> My understanding [...]

While it certainly serves as an example, I think that this is a "real plugin", but it was cloned from the template...incompletely.

**Comment by dbutenhof** [comment]
OK, I think it's used for *testing*, `run: docker-compose up` from `.github/workflows/build.yaml` ... however both that file and the accompanying `workflow.yaml` directly reference `arcaflow-plugin-template-python` as well and should probably be fixed.

**Comment by webbnh** [comment]
> OK, I think it's used for _testing_

Right, the CI runs the testing inside the container and then pulls the results out.

> `.github/workflows/build.yaml` ... however both that file and the accompanying `workflow.yaml` directly reference `arcaflow-plugin-template-python` as well and should probably be fixed.

Are you sure you're looking at the right repo?  Looking at those two files in my checkout (actually, searching _all_ the files in my checkout...), I don't see any hits on "template".  (I tried running the `set-plugin-name.sh` script and it had no effect, either.)

**Comment by dbutenhof** [comment]
> Are you sure you're looking at the right repo?

Well, I was absolutely sure yesterday, but maybe it was a GitHub Hallucination ... I certainly can't find it today. Weird.

**Review by mfleader — APPROVED** [review]

**Pull request merged**
